### PR TITLE
Create acceptance tests for ably_app resource

### PR DESCRIPTION
**Pull request by graham-russell**
- Uses the terraform SDKv2 acceptance test framework.
- Includes tests for provider + ably_app.
- Ran `go mod tidy` to update dependencies after implementing tf acceptance tests.
- Also updated Makefile to fix NAME var.

You can run the acceptance tests locally for now using `make testacc`. You will need Ably credentials set as env vars. GHA Workflow coming in separate step.

### CODE REVIEW

**Comment by graham-russell** [comment]
Example test output
```
TF_ACC=1 go test $(go list ./... | grep -v 'vendor') -v  -timeout 120m
?       terraform-provider-ably [no test files]
=== RUN   TestAccAblyApp
--- PASS: TestAccAblyApp (11.64s)
=== RUN   TestAccAblyAppDisabledStatus
    resource_ably_app_test.go:47: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to ably_app.app0, provider
        "provider[\"github.com/ably/ably\"]" produced an unexpected new value:
        .status: was cty.StringVal("disabled"), but now cty.StringVal("enabled").
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestAccAblyAppDisabledStatus (4.37s)
FAIL
FAIL    terraform-provider-ably/internal/provider       16.305s
FAIL
make: *** [testacc] Error 1
```

**Comment by kavalerov** [comment]
It is failing right now when ABLY_URL is not set - should it just fall back to default URL when no env var is set?

**Comment by graham-russell** [comment]
> It is failing right now when ABLY_URL is not set - should it just fall back to default URL when no env var is set?

I have now removed ABLY_URL from the test pre-checks.

**Review by kavalerov — APPROVED** [review]
Considering it is expected for the code right now to fail when user tries to create a "disabled" app (because of inconsistent state) - can we actually make that a "pass" for the test? 

In the future, when behaviour is improved in the API this test will fail, which will be good as it will also help us make sure that we need to update the docs at the moment (right now docs advise against creating "disabled" app)

**Review by kavalerov — CHANGES_REQUESTED** [review]
Accidentally approved, apologies. 

Considering it is expected for the code right now to fail when user tries to create a "disabled" app (because of inconsistent state) - can we actually make that a "pass" for the test?

In the future, when behaviour is improved in the API this test will fail, which will be good as it will also help us make sure that we need to update the docs at the moment (right now docs advise against creating "disabled" app)

**Review by kavalerov — APPROVED** [review]
LGTM, thanks

**Pull request merged**
