### PR TITLE
Support optional values

### PR DESCRIPTION
**Pull request by Morganamilo**
There's three things done in this commit to support optional values.

First is to also set computed on some of the optional vlaues. Setting
a field to optional and computed tells terriform that the value may come
back with a non null value after apply.

Second is to add a plan modifier that will tell terriform what the
default value will be. This is purely a visual change, it just means the
terraform plan will tell you the expected value instead of (known after
apply).

Thirdly is a bit of a special case for strings. When strings are
omitted, they are initialised to the 0 value of empty string. Terraform
does not see this as a null so it throws errors when applying. So we
adjust empty strings to null before feeding the values to terraform.

### CODE REVIEW

**Comment by graham-russell** [comment]
Looking good. The only thing I suggest we add is new push params coverage in the acceptance testing.

**Comment by Morganamilo** [comment]
Good point, I'll do that.

**Review by kavalerov — COMMENTED** [review]
Tested how optional values work, and briefly looked at the code - all looks great to me, so LGTM, thanks

**Review by kavalerov — APPROVED** [review]

**Review by kavalerov — CHANGES_REQUESTED** [review]
After further testing I've found that `tls_only` is not treated as optional at the moment, but it should (according to https://ably.com/docs/api/control-api#tag/apps/paths/~1accounts~1{account_id}~1apps/post)

**Review by kavalerov — APPROVED** [review]
Actually, if that's ok with everyone, lets merge this first as it is an improvement and adds Push notification related fields, and then fix `tls_only` separately in #91

**Comment by Morganamilo** [comment]
Yea let's do that.

**Pull request merged**
