### PR TITLE
fix(ably_api_key): Properly set the key when importing the resource

### PR DESCRIPTION
**Pull request by tete17**
If imported the state would contain null and since at no point we used the response from ably to fill it we would never override it.

I am unable to test the acceptance test since I don't personally have an ably account I won't risk it in production.

If someone can run them from me and let me know if there is any problem I am more than welcome to fix whatever comes up.

#125

### CODE REVIEW

**Comment by Morganamilo** [comment]
Hi, thanks for pointing this out, I'd not really considered how this would break when importing existing resources. However I think nulling the key is a bad idea as outputs and such would not have access to it. I think the best thing we can do here is add the key as another field of the import command. So we're not importing `<appid>,<keyid>,<key>`. What do you think?

**Comment by tete17** [comment]
Hey @Morganamilo my MR doesn't change the importing strategy it still is `<appis>,<keyid>` the only thing I changed is that when reading the value in the `Read` & `Update` function the key field is filled with the api response from the ably endpoint.

We don't need to pass the `<key>` when importing the resource it can be read programmatically.

The acceptance test I added does precisely that, we could just run it and see if it does what we expect it

**Comment by Morganamilo** [comment]
Unfortunately I don't think I can run the CI with secrets passed in.

My point about changing the import input was my suggestion on what's best to do, not what I thought you did. The issue is the control API will never tell you any secret values after the initial creation. So it can't be read problematically.

This PR will just allow it to be null instead of erroring. But in reality a key is never null, so this is why instead I think we should not allow key to be null and require you to specify it on import.

**Comment by tete17** [comment]
Hi @Morganamilo 

I did a quick test against the api `https://control.ably.net/v1/apps/{app_id}/keys` and as I expected the full keys are returned. This means we don't need to give the private key as part of the import process.

Here is my response

```
[
  {
    "app_id": "REDACTED"
    "id": "REDACTED"
    "name": "Root",
    "key": "REDACTED"
    ...
  }
]
```


My suspicions came from the fact that in the Ably UI you can get the full api key. I suspect the ably ui is a simple wrapper around the api so it only made sense that functionality was on par with the api.

The tests seem to be made to be run in a special integration environment from ably. Anyway you could run the tests locally to make sure it actually works.

**Comment by Morganamilo** [comment]
Hey there. I've been on holiday sorry. When I started building this the API would not return secrets but it appears it does now? I need to see what's going on as it's a different team that works on the control API.

**Comment by tete17** [comment]
Hi @Morganamilo no worries.

Keep me updated on what your findings I still think the approach of not needing the key in the import statement is prefered as long as the key is provided through the api.

**Comment by tete17** [comment]
Hey @Morganamilo any updates?

**Comment by tete17** [comment]
Hey @Morganamilo you **STOLE** my code [here](https://github.com/ably/terraform-provider-ably/pull/137) and took the credit for it.

There is no point in having this opened any more a friendly notification for my effort put into making the ticket https://github.com/ably/terraform-provider-ably/issues/125 and this MR would have been nice, although I would have prefer not to have been robbed away.

Don't expect any more contributions from me or my company on any other ably products and I will recommend my company to move away from you guys as soon as we can.

**Pull request closed without merging**
