### PR TITLE
[IAC-43] Create Ably App Datasource

### PR DESCRIPTION
**Pull request by graham-russell**
Includes:
- Documentation updates (terraform-docs + tfplugindocs)
- Examples in resources + playground folders. Creates an app datasource and demonstrates use with tf outputs.
- Ably App Datesource code + Acceptance tests
- Update provider.go to expose app datasource.

### CODE REVIEW

**Comment by Morganamilo** [comment]
This is a lot of duplicated code? Will we have to do this for every resource type? Can't we do it with one type? Can we have the app resource implement the resource and data interfaces?

**Comment by graham-russell** [comment]
> This is a lot of duplicated code? Will we have to do this for every resource type? Can't we do it with one type? Can we have the app resource implement the resource and data interfaces?

Agreed, In part, this is one of the reasons I logged this PR ahead of schedule as it'll give us time to formulate a plan on how to proceed.
Let's discuss this one and agree on an approach with the team.

**Comment by kavalerov** [comment]
This is the new approach, right?

**Comment by kavalerov** [comment]
Considering that we are not likely to merge this in the near future - should we maybe move the PR into "draft" stage? It is "waiting for reviews" right now.

**Comment by graham-russell** [comment]
We can probably go further and close this PR for now. It can be reopened when we implement datasources. wdyr @kavalerov ?

**Comment by kavalerov** [comment]
Agreed. Lets do this.

**Pull request closed without merging**
