### PR TITLE
Implement ably_app resource Read functionality

### PR DESCRIPTION
**Pull request by graham-russell**
From the terraform related docs:
The provider uses the Read function to retrieve the resource's information and update the Terraform state to reflect the resource's current state. The provider invokes this function before every apply to generate an accurate diff between the resource's current state and the configuration.

### CODE REVIEW

**Comment by kavalerov** [comment]
Is this invoked when running `terraform apply -refresh-only`? I.e. if I run refresh, should it update local state to reflect the changes made remotely?

**Comment by kavalerov** [comment]
Just to be clear, the reason I am asking is because it doesn't seem to work this way for me. 


My terraform file: 
```
resource "ably_app" "app0" {
  name                      = "ably-tf-provider-app-0000"
  status                    = "enabled"
  tls_only                  = true
}
```

I ran `terraform plan` and `terraform apply`.

Then I went online, and updated the app: 

Screenshot 2022-08-09 at 17 46 48

And then when I run `terraform apply -refresh-only` I get the following: 
```
ably_app.app1: Refreshing state... [id=gqc1lw]
ably_app.app0: Refreshing state... [id=hPj47Q]

No changes. Your infrastructure still matches the configuration.

Terraform has checked that the real remote objects still match the result of your most recent changes, and found no differences.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

And if I check the state file manually, the corresponding part is not updated: 
```
...
"resources": [
    {
      "mode": "managed",
      "type": "ably_app",
      "name": "app0",
      "provider": "provider[\"github.com/ably/ably\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_id": "FRACpQ",
            "id": "hPj47Q",
            "name": "ably-tf-provider-app-0000",
            "status": "enabled",
            "tls_only": true
          },
          "sensitive_attributes": []
        }
      ]
    },
...
```

**Comment by graham-russell** [comment]
Have you rebuilt the provider locally @kavalerov?

**Comment by graham-russell** [comment]
The reason I ask is @kavalerov is that I've been testing locally (Using one of the upcoming tests in the suite) as well as running play/apply and it works as expected.

Do note that because the update functionality hasn't been implemented in the PR, State won't be updated. The Read method is used to generate a diff.

Example output
```
ably_app.app0: Refreshing state... [id=MKN3rw]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # ably_app.app0 will be updated in-place
  ~ resource "ably_app" "app0" {
      ~ account_id = "wfet4A" -> (known after apply)
      ~ id         = "MKN3rw" -> (known after apply)
        name       = "ably-tf-provider-app-00050"
      ~ tls_only   = false -> true
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by kavalerov** [comment]
Sorry for this - I thought I responded, but the got to a customer call and never came back. 
yes, you are right - it was my mistake, after `go install` everything works 🤦

**Comment by kavalerov** [comment]
Btw, was this supposed to be closed? There are still unmerged commits.

**Comment by graham-russell** [comment]
> Btw, was this supposed to be closed? There are still unmerged commits.
Mistakenly closed. Have reopened now.

**Review by kavalerov — COMMENTED** [review]
LGTM, thanks!

**Review by kavalerov — APPROVED** [review]

**Pull request merged**
