### PR TITLE
0.3.0 Release

### PR DESCRIPTION
**Pull request by kavalerov**

### CODE REVIEW

**Comment by kavalerov** [comment]
@Morganamilo or @graham-russell  - do you know by any chance why the check may be failing? I don't see how anything in this PR could've impacted this....

**Comment by graham-russell** [comment]
> @Morganamilo or @graham-russell - do you know by any chance why the check may be failing? I don't see how anything in this PR could've impacted this....

Looks like an error with the staging queue system. Try rerunning the failing check as I suspect that the error was temporary.

**Review by QuintinWillison — APPROVED** [review]

**Comment by kavalerov** [comment]
The job keeps on failing...

**Comment by kavalerov** [comment]
Which is also confusing as, for example, checks in the next door PR (https://github.com/ably/terraform-provider-ably/pull/131) ran successfully an hour ago. I am rerunning once again - hope this time it will work better.

**Comment by kavalerov** [comment]
Merging as checks have passed + approval was received + if we do any additional fixes, we will release them in a followup release.

**Pull request merged**
