### PR TITLE
Implement Ably Rule Resource with Azure Functions Target

### PR DESCRIPTION
**Pull request by graham-russell**
This PR includes the following items
- tfplugindocs generated documentation
- Ably Azure Functions integration rule resource with inbuilt source and target.
- Updates to provider and models to represent Ably Rule for Azure Functions target
- Playground tf templates updated
- Resource example updated for Azure Functions integration rule
- Acceptance testing configured

### CODE REVIEW

**Comment by graham-russell** [comment]
Also note that I haven't included the `enveloped` parameter for the Azure function because I receive the following error when it's included:
Screenshot 2022-09-21 at 11 11 10

**Comment by Morganamilo** [comment]
> Also note that I haven't included the `enveloped` parameter for the Azure function because I receive the following error when it's included: Screenshot 2022-09-21 at 11 11 10

Try batch mode :P

**Comment by kavalerov** [comment]
We should probably raise that behaviour as a Control API and web bug with the web team as well.

**Comment by graham-russell** [comment]
> > Also note that I haven't included the `enveloped` parameter for the Azure function because I receive the following error when it's included: Screenshot 2022-09-21 at 11 11 10
> 
> Try batch mode :P

Tried with batch mode again to confirm and still received the error. Using the following terraform template

```terraform
resource "ably_rule_azure_function" "rule0" {
  app_id = ably_app.app0.id
  status = "enabled"
  source = {
    channel_filter = "^my-channel.*",
    type           = "channel.message"
  }
  request_mode = "batch"
  target = {
    azure_app_id  = "coms",
    function_name = "function0"
    headers = [
      {
        name : "User-Agent",
        value : "user-agent-string",
      },
      {
        name : "User-Agent-Extra",
        value : "user-agent-string",
      },
    ]
    signing_key_id = ably_api_key.api_key_1.id
    format         = "json"
    enveloped = true
  }
}
```

**Comment by Morganamilo** [comment]
So maybe this one doesn't support enveloped at all either way? hmm

**Comment by graham-russell** [comment]
> So maybe this one doesn't support enveloped at all either way? hmm

Yeah, I'll track this down and figure out what's happening. The documentation included 'enveloped' as a param but it definitely fails with including in regardless of the request mode.

For now I'd suggest we review this without `enveloped` and then submit a follow up PR depending on the feedback we get from the team.

**Review by Morganamilo — APPROVED** [review]

**Comment by Morganamilo** [comment]
In my current PR i moved the header loop to it's own function. I'll have to rebase that PR after this merges.

**Pull request merged**
